language: php

php:
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - mysql -e 'create database translation_behavior_yii2_tests;'
  - php ./tests/yii migrate --migrationPath=./tests/migrations --interactive=0

script:
  - vendor/bin/phpunit
  